plugins { id 'com.android.application' }

android {
    namespace 'com.example.androidautobuildapk'
    compileSdk 35
    
    defaultConfig {
        applicationId "com.example.androidautobuildapk"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    // KONFIGURASI SPLIT APK
    splits {
        abi {
            enable true
            reset()
            include "arm64-v8a", "armeabi-v7a" // Membuat 2 APK berbeda
            universalApk false // Jangan buat APK gabungan
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
            signingConfig signingConfigs.debug
        }
    }
    
    packagingOptions {
        jniLibs { useLegacyPackaging = false }
    }
}
