plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.example.androidautobuildapk'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.androidautobuildapk"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"
        
        ndk {
            // Filter ABI agar APK tetap ramping
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
    }

    // Solusi untuk error "Inconsistent JVM-target"
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = '17'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
}
