[package]
name = "vuzt_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21.1"

[profile.release]
opt-level = "z"      # Optimasi ukuran paling ekstrem
lto = true           # Link Time Optimization
codegen-units = 1    # Membuat proses kompilasi lebih fokus pada ukuran
panic = "abort"      # Menghilangkan kode unwinding stack
strip = true         # Menghapus simbol debug secara otomatis
