[package]
name = "vuzt_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.21.1", default-features = false }

[profile.release]
opt-level = "z"     # Optimasi ukuran terkecil
lto = true          # Link Time Optimization penuh
codegen-units = 1   # Maksimalkan optimasi antar file
panic = "abort"     # Hapus overhead panic-handler (anti-crash)
strip = true        # Buang simbol-simbol nama fungsi
