name: Build Rust-Kotlin APK

on:
  push:
    branches: [ rust, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Cache Rust & Cargo
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            app/src/main/rust/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi

      - name: Install cargo-ndk
        run: cargo install cargo-ndk || true # || true agar tidak error jika sudah ada di cache

      - name: Build Rust Native Library
        run: |
          cd app/src/main/rust
          # Compile untuk ARM64
          cargo ndk -t arm64-v8a -o ../jniLibs/ build --release
          # Compile untuk ARMv7
          cargo ndk -t armeabi-v7a -o ../jniLibs/ build --release

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: rust-v${{ github.run_number }}
          name: Rust Build v${{ github.run_number }}
          files: app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
